### ISSUE TITLE
Sniper Rifle A_ZoomFactor minor issue

### ISSUE THREAD

**Issue by popguy12** [Lewisk3/HaloDoom_GZDoomVersion#1]
Sniper Rifle does not reset Zoom factor back to normal all the way after firing, switching away and switching back resets all the way.
firing while scoped does not have this issue either

**Comment by Lewisk3** [comment]
Fixed in https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/0f0efe8e5090649393bf1b63a8b6d50af5c7e6d1
