### ISSUE TITLE
Have the 'Unlimited Weapon capacity' cheat respect 'Switch on pickup' setting

### ISSUE THREAD

**Issue by czrcceo** [Lewisk3/HaloDoom_GZDoomVersion#11]
Currently when 'Switch on pickup' is off it switches weapon anyway

**Comment by Lewisk3** [comment]
Should work now. 
https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/0702c6caaf295e2c2076bf0d31da0e17a5ad3025

**Comment by czrcceo** [comment]
It works perfectly, cheers!
