### ISSUE TITLE
How do I setup to play this mod?

### ISSUE THREAD

**Issue by coreybruce** [Lewisk3/HaloDoom_GZDoomVersion#14]
Hey I want to play this but it won't work for me and I can't find any documentation or instructions for this, I have the pk3 file in the same folder as the GZDoom binary and it just goes into Doom instead. am I doing something wrong? 

![image](https://github.com/Lewisk3/HaloDoom_GZDoomVersion/assets/8393780/6261efd4-265a-488f-b235-af99b27ac121)

**Comment by coreybruce** [comment]
I figured it out for some reason I had to do this

```
./gzdoom "Halo Doom Evolved Season 3.1 Hotfix ModDB.pk3"
```

**Comment by Lewisk3** [comment]
GZDoom takes a `-file` argument as well, so for example `gzdoom -file "PathToModHere"` will work as well.
I recommend using a mod-loader, such as ZDL (https://github.com/lcferrum/qzdl) or Doom Runner (https://github.com/Youda008/DoomRunner) if you're more comfortable with a GUI rather than CLI.
