### ISSUE TITLE
HUD Key Marker

### ISSUE THREAD

**Issue by popguy12** [Lewisk3/HaloDoom_GZDoomVersion#2]
HUD marker for Keys is slightly offcenter, causing it to move slightly as the key rotates
the displaying of the markers as well tends to lag behind a couple tics as well, but that can be changed at a different point in time as its not a big issue

**Comment by Lewisk3** [comment]
> HUD marker for Keys is slightly offcenter, causing it to move slightly as the key rotates

This was just the result of some offsets passed to the HUD projection, fixed.
> the displaying of the markers as well tends to lag behind a couple tics as well

There is no concept of tics from the UI scope, so that's definitely not happening. 
Not sure what could be causing the apparent lag, I'll look into it though.

**Comment by popguy12** [comment]
yea i was mainly usin tics as a point of reference, i know it doesnt exactly exist in the UI itself

**Comment by Lewisk3** [comment]
Fixed in https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/432ba17942b8e0ac04f2e3ce8e1137d18a155398
