### ISSUE TITLE
Issues with shootable/damageable triggers and obstacles

### ISSUE THREAD

**Issue by JediMasterChief** [Lewisk3/HaloDoom_GZDoomVersion#6]
This was on the latest dev build as of this writing (commit f3a4ee04dd23b79979a73ab71e96c6b33f6c4c70).

In E1M2, the melee attack is unable to trigger the wall secret to lower, though shooting it does work.

In Sigil's E5M1, and I imagine other shootable triggers requiring hitscan, Halo Doom's weapons are unable to activate them. In E5M1 specifically, shooting the trigger enough will cause the small part of the wall it is behind to lower, but the player will still be trapped in the starting area. For this part, I think MetaDoom actually had a solution that allowed its projectile pistol to work, if you want to look into that.

In Extermination Day's first level, the melee attack has trouble activating the broken button. It is possible, but fails more often than not, requiring multiple punches before it triggers. It is also unable to destroy grates and some other objects.

There might be other issues, but this is all I found as of know. If others report anything or I find more, I will add them here.

**Comment by Lewisk3** [comment]
The issues have been addressed in https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/238b7f2c50af89cf00a759c08ae394b0d3cb1ab7

I've tested E1M2, Sigil and EDay (Vanilla & Mod compatible version) all of which appear to function fine now.

**Comment by JediMasterChief** [comment]
I'll give it a test run to try it out in the near future. Thank you.

**Comment by JediMasterChief** [comment]
> The issues have been addressed in [238b7f2](https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/238b7f2c50af89cf00a759c08ae394b0d3cb1ab7)
> 
> I've tested E1M2, Sigil and EDay (Vanilla & Mod compatible version) all of which appear to function fine now.

Update: E1M2 and EDay are fixed fixed. However, Sigil is still proving to have problems on my end. Though it is easier to trigger the button, though still inconsistent, the wall out of the room still does not lower once the trigger is activated. I made sure no other mods were interfering.

**Comment by Lewisk3** [comment]
> Sigil is still proving to have problems on my end. Though it is easier to trigger the button, still being inconsistent, the wall out of the room still does not lower once the trigger is activated. I made sure no other mods were interfering.

I cannot replicate this issue, I've played the first 6 maps of Sigil without issue so far.

**Comment by JediMasterChief** [comment]
> > Sigil is still proving to have problems on my end. Though it is easier to trigger the button, still being inconsistent, the wall out of the room still does not lower once the trigger is activated. I made sure no other mods were interfering.
> 
> I cannot replicate this issue, I've played the first 6 maps of Sigil without issue so far.

I wonder what is going on with my setup, then. I can try redownloading Sigil to see if my copy somehow got corrupted. May also try a fresh config file.

**Comment by JediMasterChief** [comment]
> > Sigil is still proving to have problems on my end. Though it is easier to trigger the button, still being inconsistent, the wall out of the room still does not lower once the trigger is activated. I made sure no other mods were interfering.
> 
> I cannot replicate this issue, I've played the first 6 maps of Sigil without issue so far.

Is your version of Sigil 1.1? I tried that version, and it is indeed working on my end. I was using the most recent version on Romero's website, 1.21.

**Comment by Lewisk3** [comment]
Figured out a solution, issue should be fixed now. https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/aa8bfbd4a43cd2dd65e226404bfba1bac3484916

Do give it a test, if everything is working right then I'll close this issue.

**Comment by JediMasterChief** [comment]
Gave it a test, and its working now. Thank you. I'll report more issues as I find them.
