### ISSUE TITLE
Spiker projectiles seem to cause VM Aborts (image include)

### ISSUE THREAD

**Issue by JediMasterChief** [Lewisk3/HaloDoom_GZDoomVersion#8]
I've had various outputs. This is the latest one.

![SpikerError](https://user-images.githubusercontent.com/38988420/160221505-3d35823e-9c52-43b7-957a-632e79428f73.PNG)

**Comment by Lewisk3** [comment]
Fixed in https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/10afd673ea05ca29802eb3ca19cc1c699227f2be
