### ISSUE TITLE
Main Menu Unable to load

### ISSUE THREAD

**Issue by JediMasterChief** [Lewisk3/HaloDoom_GZDoomVersion#9]
![MenuError](https://user-images.githubusercontent.com/38988420/160461159-6c41861c-526d-4b46-b08c-fd486d618664.PNG)

In addition, attempting to rename intromus to titlemus does not fix the issue, and additionally mentions intromus being missing. Having both just displays the above error. I also noticed the intromusic file is actually in wav format rather than ogg. Renaming one of the other titlemus files does not stop the crash either, just mentioning the same line in overlay_ui.zsc as the error above.

**Comment by Lewisk3** [comment]
Fixed https://github.com/Lewisk3/HaloDoom_GZDoomVersion/commit/0a1ae55573994af49b6844c84b7a211f9a090c6f
